### ISSUE TITLE
Cannot Create Public Certificate via ENV Var

### ISSUE THREAD

**Issue by doyler86** [ca-api-gateway/gateway-developer-plugin#188]
**Is your feature request related to a problem? Please describe.**
Yes, i tried to follow the following format to create a pub cert, but it seems it's choking on my serial number. My ask is, can we update the wiki to show a real example of how to use a cert from a gateway, and access the information needed to eventually source that same cert as an ENV Var

ENV.CERTIFICATE.my-cert: '{
                           "verifyHostname" : false,
                           "trustedForSsl" : true,
                           "trustedAsSamlAttestingEntity" : false,
                           "trustAnchor" : true,
                           "revocationCheckingEnabled" : true,
                           "trustedForSigningClientCerts" : true,
                           "trustedForSigningServerCerts" : true,
                           "trustedAsSamlIssuer" : false,
                           "certificateData" : {
                             "issuerName" : "Trusted Secure Certificate Authority 5",
                             "serialNumber" : "21091060503b26de1b4430fdc5dca84c",[<---- this seems to be choking]
                             "subjectName" : "gtwd.primericaonline.com",
                             "encodedData" : "Base64 Encoded .PEM"[not sure this is correct]
                           }
                         }'

**Describe the solution you'd like**
A clear and concise description on how to populate the Pub Cert ENV Var

**Describe alternatives you've considered**
N.A.
**Additional context**
N.A.

**Comment by joao-borges** [comment]
Hi @doyler86, I will investigate this and get back to you,

**Comment by joao-borges** [comment]
@doyler86 Your JSON It's almost right, just small modifications:

ENV.CERTIFICATE.my-cert: '{
	"verifyHostname" : false,
	"trustedForSsl" : true,
	"trustedAsSamlAttestingEntity" : false,
	"trustAnchor" : true,
	"revocationCheckingEnabled" : true,
	"trustedForSigningClientCerts" : true,
	"trustedForSigningServerCerts" : true,
	"trustedAsSamlIssuer" : false,
	"certificateData" : {
	   **"issuerName" : "CN=Trusted Secure Certificate Authority 5", #OU, O and C are optional**
	   **"serialNumber" : 121321321313131132131, #This has to be only numbers**
	   "subjectName" : "gtwd.primericaonline.com",
	   "encodedData" : "Base64 Encoded Cert Data" **#that's correct**
	}
}'

Please confirm that it works.

Thanks,
Joao

**Comment by doyler86** [comment]
Thanks @joao-borges ,

This is what i have now(notice the letters in the serial number),

ENV.CERTIFICATE.my-cert: '{
                           "verifyHostname" : false,
                           "trustedForSsl" : true,
                           "trustedAsSamlAttestingEntity" : false,
                           "trustAnchor" : true,
                           "revocationCheckingEnabled" : true,
                           "trustedForSigningClientCerts" : true,
                           "trustedForSigningServerCerts" : true,
                           "trustedAsSamlIssuer" : false,
                           "certificateData" : {
                             "issuerName" : "CN=Trusted Secure Certificate Authority 5",
                             "serialNumber" : 21091060503b26de1b4430fdc5dca84c,
                             "subjectName" : "gtwd.primericaonline.com",
                             "encodedData" : "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUhTVENDQmpHZ0F3SUJBZ0lRSVFrUVlGQTdKdDRiUkREOXhkeW9UREFOQmdrcWhraUc5dzBCQVFzRkFEQ0IKaGpFTE1Ba0dBMVVFQmhNQ1ZWTXhDekFKQmdOVkJBZ1RBa1JGTVJNd0VRWURWUVFIRXdwWGFXeHRhVzVuZEc5dQpNU1F3SWdZRFZRUUtFeHREYjNKd2IzSmhkR2x2YmlCVFpYSjJhV05sSUVOdmJYQmhibmt4THpBdEJnTlZCQU1UCkpsUnlkWE4wWldRZ1UyVmpkWEpsSUVObGNuUnBabWxqWVhSbElFRjFkR2h2Y21sMGVTQTFNQjRYRFRFNE1USXkKT0RBd01EQXdNRm9YRFRJd01USXlOekl6TlRrMU9Wb3dnY3N4Q3pBSkJnTlZCQVlUQWxWVE1RNHdEQVlEVlFRUgpFd1V6TURBNU9URUxNQWtHQTFVRUNCTUNSMEV4RHpBTkJnTlZCQWNUQmtSMWJIVjBhREVaTUJjR0ExVUVDUk1RCk1TQlFjbWx0WlhKcFkyRWdVR3QzZVRFcU1DZ0dBMVVFQ2hNaFVGSkpUVVZTU1VOQklFWkpUa0ZPUTBsQlRDQlQKUlZKV1NVTkZVeXdnVEV4RE1Rc3dDUVlEVlFRTEV3SkpWREVYTUJVR0ExVUVDeE1PUlc1MFpYSndjbWx6WlNCVApVMHd4SVRBZkJnTlZCQU1UR0dkMGQyUXVjSEpwYldWeWFXTmhiMjVzYVc1bExtTnZiVENDQVNJd0RRWUpLb1pJCmh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVYxc1hac0Z3NU1GeFJmbkRzdW4xaW51bCt2UmRobGtKNUgKd3NrVU5mSW9ycmRyMGVZNjk2RXV5OERBdU5uZ2Y1NVRFL2hCMW1qaTJpZEc3TlhlMFc4YlF2WVZUVDNUZ010VwptSmF2SlVNTCtxUWJkL1JoMCsvVVRCbnlyNHdhSTEydXlsQ1ZNOVBWRDlxZ0VsVlJoRjl5Yy94SVdBUUhyNjlrCnMyMllRTEVoSTZlMmRNRVpPRjB2UHF6eHQ5TWlQQmVFL2NlS2V0NDBFNEI3UWUwR096RGx4SVdDWk84aDkyVjYKVjNrRjZaN2pSNEQxVU1ENEVYRDIvTW5CcXRUbnhmakl4OHRkNUViN1puenVuSmVHRGFXc1kyOGRWa3kyU2cvbwp0OExhaWhuYitGUU55b0FIUkRpT2xrWnh1TnM1Nm1FQVBlaGlpT05rYmNFYXFQT283dnNDQXdFQUFhT0NBMm93CmdnTm1NQjhHQTFVZEl3UVlNQmFBRlBLN1ZlNzhqOC9RUHhSb0dwVitlUTZyRnpEME1CMEdBMVVkRGdRV0JCVG4KeGVPdzJETUw2Y0xyRlRSblVjQnUvOFBMSmpBT0JnTlZIUThCQWY4RUJBTUNCYUF3REFZRFZSMFRBUUgvQkFJdwpBREFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd1N3WURWUjBnQkVRd1FqQTJCZ3NyCkJnRUVBYkl4QVFJQ0NEQW5NQ1VHQ0NzR0FRVUZCd0lCRmhsb2RIUndjem92TDJOd2N5NTFjMlZ5ZEhKMWMzUXUKWTI5dE1BZ0dCbWVCREFFQ0FqQlFCZ05WSFI4RVNUQkhNRVdnUTZCQmhqOW9kSFJ3T2k4dlkzSnNMblZ6WlhKMApjblZ6ZEM1amIyMHZWSEoxYzNSbFpGTmxZM1Z5WlVObGNuUnBabWxqWVhSbFFYVjBhRzl5YVhSNU5TNWpjbXd3CmdZSUdDQ3NHQVFVRkJ3RUJCSFl3ZERCTEJnZ3JCZ0VGQlFjd0FvWS9hSFIwY0RvdkwyTnlkQzUxYzJWeWRISjEKYzNRdVkyOXRMMVJ5ZFhOMFpXUlRaV04xY21WRFpYSjBhV1pwWTJGMFpVRjFkR2h2Y21sMGVUVXVZM0owTUNVRwpDQ3NHQVFVRkJ6QUJoaGxvZEhSd09pOHZiMk56Y0M1MWMyVnlkSEoxYzNRdVkyOXRNRUVHQTFVZEVRUTZNRGlDCkdHZDBkMlF1Y0hKcGJXVnlhV05oYjI1c2FXNWxMbU52YllJY2QzZDNMbWQwZDJRdWNISnBiV1Z5YVdOaGIyNXMKYVc1bExtTnZiVENDQVg0R0Npc0dBUVFCMW5rQ0JBSUVnZ0Z1QklJQmFnRm9BSFlBdTluZnZCK0tjYldUbENPWApxcEo3UnpoWGxRcXJVdWdha0paa05vNGUwWVVBQUFGbjlmNFhjd0FBQkFNQVJ6QkZBaUI0TEZLQXlxVC9MUkhxCnYxdmdscnQwNTlNK0Z6TjducUtPN3B1YXJuZm5lUUloQVB0b3pDRjVUT1FWbXRDRFpZaVlxMnNrUDVOemtKYkkKemZXR1AvSW1SSHNxQUhZQVhxZHorZDlXd09lMU5raDkwRW5nTW5xUm1neUVvUklTaEJoMWxvRnhSVmdBQUFGbgo5ZjRYMGdBQUJBTUFSekJGQWlBQklPV0VXd3dNTG5YVEtMZnFrZy91WWtpRWszM21ZdUN3MmEyL2pxditMd0loCkFNaFhDYnBleGRCVTVqYjJLWnMwOEt2UFQ0YXZ0NWVkeG5kY001UnNCZHF5QUhZQThKV2tXZklBMFlKQUVDMHYKazRpT3JVditIVWZqbWVIUU5LYXdxS3FPc25NQUFBRm45ZjRYdmdBQUJBTUFSekJGQWlFQWtmUis0aXhWVXFDRAoyRGN6dTY1TnkyOTczc3Q0QUdMY2hlY0VIT3VObVRjQ0lHVUE0NHNHN29HOS84L2RSTFU5SVpqYWdRY0lBSFdvCjB2TmdNTWhOTEw2Yk1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTVJSUdOOFFKbHI1RnJFSUFRbUdaR0JvcTAKUVg5MDlTSzdRY282ZlZZWFBBS3FlU2V5YWhXbnpySGw1Y29vUjdocHlhMEhKb2llWDdUd2NLU1c4YTNqbTAxWApERU5lTU53OU5rMFRpcFhvTmlmYkJCald4OUhuVW83NkJxV1FldjNkdkE4bTlEb20vWVRDRHd0VXhYeUY3OVlTCmR5Y0czQ1drbFptVmYyZWdlLzNEemlTL2FyaHh0Mmc1UW5VNU9Xc2VCL1JXNWdpMlkxek5zcXdPZklmMG5iaUIKQVNCTmJFTFJDUU9GSmlYY1Q2QkVNTjkweEc4a1cxQUFuZ3VOd1J0V3pKUWkzOElGRGFEYkE1S204RXRRdld4dwoyVjlaaE9FWTNEZzdEVWlkN3JFeVlIS1JGa0N5UWlVVC9ZVnB3ZjlyOU5Eak9sY3VVUXNtaThzdm9BK1MKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="
                           }
                         }'

and seeing this in the logs 

Running script /opt/docker/rc.d/apply-environment.sh
[main] INFO org.reflections.Reflections - Reflections took 71 ms to scan 2 urls, producing 35 keys and 238 values 
Exception in thread "main" com.ca.apim.gateway.cagatewayconfig.util.json.JsonToolsException: Could not parse configuration file for type: Lcom/ca/apim/gateway/cagatewayconfig/beans/TrustedCert; Message:Unexpected character ('b' (code 98)): was expecting comma to separate Object entries
 at [Source: (ByteArrayInputStream); line: 1, column: 359] (through reference chain: com.ca.apim.gateway.cagatewayconfig.beans.TrustedCert["certificateData"])
        at com.ca.apim.gateway.cagatewayconfig.util.json.JsonTools.readStream(JsonTools.java:114)
        at com.ca.apim.gateway.cagatewayconfig.config.loader.EntityLoaderBase.load(EntityLoaderBase.java:74)
        at com.ca.apim.gateway.cagatewayconfig.environment.EnvironmentBundleBuilder.addEnvToBundle(EnvironmentBundleBuilder.java:88)
        at com.ca.apim.gateway.cagatewayconfig.environment.EnvironmentBundleBuilder.lambda$build$1(EnvironmentBundleBuilder.java:43)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$0(Collections.java:1575)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet$UnmodifiableEntrySetSpliterator.forEachRemaining(Collections.java:1600)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at com.ca.apim.gateway.cagatewayconfig.environment.EnvironmentBundleBuilder.build(EnvironmentBundleBuilder.java:43)
        at com.ca.apim.gateway.cagatewayconfig.environment.EnvironmentBundleCreator.createEnvironmentBundle(EnvironmentBundleCreator.java:55)
        at com.ca.apim.gateway.cagatewayconfig.EnvironmentCreatorApplication.run(EnvironmentCreatorApplication.java:85)
        at com.ca.apim.gateway.cagatewayconfig.EnvironmentCreatorApplication.main(EnvironmentCreatorApplication.java:64)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Unexpected character ('b' (code 98)): was expecting comma to separate Object entries
 at [Source: (ByteArrayInputStream); line: 1, column: 359] (through reference chain: com.ca.apim.gateway.cagatewayconfig.beans.TrustedCert["certificateData"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3084)
        at com.ca.apim.gateway.cagatewayconfig.util.json.JsonTools.readStream(JsonTools.java:112)
        ... 19 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('b' (code 98)): was expecting comma to separate Object entries
 at [Source: (ByteArrayInputStream); line: 1, column: 371]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:669)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:567)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:978)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:295)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        ... 23 more
ERROR - Failed executing the script: /opt/docker/rc.d/apply-environment.sh



Seems the letters are choking the 'apply-environment' script..

so my ask is, how do i get the serial number in the correct format?

Here's a snapshot of what im working with,

![image](https://user-images.githubusercontent.com/13688489/53104175-7fa9a680-34f4-11e9-9727-89b64a5a2ce4.png)

**Comment by joao-borges** [comment]
@doyler86 The serial number should be a 'number' unfortunately we do not accept it in hexadecimal format.
You can google for 'hex to decimal converter', copy the serial number to convert to decimal format and apply to your environment. Then it will work.

I don't know if is possible but you can do something like this:

```
ENV.CERTIFICATE.https://gtwd.primericaonline.com: '{
...
}
```
If you do this, you don't need to specify the cert data into the json, the plugin will retrieve it from the URL.
But for this, your environment need to have access to the URL.

Please come back if you have any issues. 

Thanks
Joao

**Comment by yves-chan** [comment]
@doyler86, Alternatively, you can omit the certificateData part and reference your cert using CERTIFICATE_FILE like so:
```json
      ENV.CERTIFICATE.my-cert: |-
        {
          "verifyHostname": false,
          "trustedForSsl": true,
          "trustedAsSamlAttestingEntity": false,
          "trustAnchor": true,
          "revocationCheckingEnabled": true,
          "trustedForSigningClientCerts": true,
          "trustedForSigningServerCerts": true,
          "trustedAsSamlIssuer": true
        }
      ENV.CERTIFICATE_FILE.my-cert.pem: |-
        -----BEGIN CERTIFICATE-----
        <encoded base64>
        -----END CERTIFICATE-----
```
This will automagically generate the certificate data for you. Give that a try. We seem to have left that part out in the docs, I will update the wiki

**Comment by joao-borges** [comment]
Hi @doyler86, does our suggestions worked out for you?

**Comment by doyler86** [comment]
My apologies, i thought i replied back to this, yes, this worked for me, thank you so much!!

**Comment by amoghsa** [comment]
Closing issue in that case.
